name: Build TWRPPPGen

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      id: date
      run:  |
        chmod +x Build.sh && \
        ./Build.sh && \
        echo "::set-output name=today::$(date +"%d-%m-%y--%H-%M-%S")"
    
    - uses: actions/upload-artifact@v2
      with:
       name: Output
       path: /home/runner/work/TWRPPPGen/TWRPPPGen/build/DEBUG-TWRPPPGen.exe
